# gen_ast_err_h.cmake
#
# Generate ast_err.h from ast_err.msg
#
# This replaces the Starlink MESSGEN utility for the purposes of
# generating the C error header file. It parses the .msg file format
# and produces a C header with the same error code values that
# MESSGEN would produce.
#
# Usage:
#   cmake -DINPUT=ast_err.msg -DOUTPUT=ast_err.h -P gen_ast_err_h.cmake

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "INPUT and OUTPUT must be defined")
endif()

file(READ "${INPUT}" msg_contents)

# Convert to a list of lines
string(REGEX REPLACE "\r?\n" ";" lines "${msg_contents}")

set(facility_name "")
set(facility_code 0)
set(prefix "")
set(severity 0)
set(base 0)
set(message_number 0)
set(output_lines "")

foreach(line IN LISTS lines)
    # Strip leading/trailing whitespace
    string(STRIP "${line}" line)

    # Skip empty lines and comments
    if("${line}" STREQUAL "" OR "${line}" MATCHES "^!")
        continue()
    endif()

    # Parse .TITLE directive
    if("${line}" MATCHES "^\\.TITLE[ \t]+([A-Za-z_]+)")
        set(facility_name "${CMAKE_MATCH_1}")
        continue()
    endif()

    # Parse .FACILITY directive: name,number/PREFIX=prefix
    if("${line}" MATCHES "^\\.FACILITY[ \t]+([A-Za-z_]+),([0-9]+)/PREFIX=([A-Za-z_]+)")
        set(facility_name "${CMAKE_MATCH_1}")
        set(facility_code "${CMAKE_MATCH_2}")
        set(prefix "${CMAKE_MATCH_3}")
        continue()
    endif()

    # Parse .SEVERITY directive
    if("${line}" MATCHES "^\\.SEVERITY[ \t]+([A-Z]+)")
        set(sev_name "${CMAKE_MATCH_1}")
        if("${sev_name}" STREQUAL "WARNING")
            set(severity 0)
        elseif("${sev_name}" STREQUAL "SUCCESS")
            set(severity 1)
        elseif("${sev_name}" STREQUAL "ERROR")
            set(severity 2)
        elseif("${sev_name}" STREQUAL "INFORMATIONAL")
            set(severity 3)
        elseif("${sev_name}" STREQUAL "SEVERE")
            set(severity 4)
        endif()
        continue()
    endif()

    # Parse .BASE directive
    if("${line}" MATCHES "^\\.BASE[ \t]+([0-9]+)")
        set(base "${CMAKE_MATCH_1}")
        set(message_number "${base}")
        continue()
    endif()

    # Parse .END directive
    if("${line}" MATCHES "^\\.END")
        break()
    endif()

    # Parse message definition: NAME <description>
    if("${line}" MATCHES "^([A-Za-z_0-9]+)[ \t]+<(.*)>")
        set(msg_name "${CMAKE_MATCH_1}")
        set(msg_desc "${CMAKE_MATCH_2}")

        # Compute error code using the Starlink MESSGEN formula:
        # errcode = ((fac_code | 0x800) << 16) + ((message_number | 0x1000) << 3) + severity
        math(EXPR fac_shifted "(${facility_code} | 2048) << 16")
        math(EXPR msg_shifted "(${message_number} | 4096) << 3")
        math(EXPR errcode "${fac_shifted} + ${msg_shifted} + ${severity}")

        # Format with padding to match MESSGEN output style
        string(LENGTH "${prefix}${msg_name}" name_len)
        math(EXPR pad_len "20 - ${name_len}")
        if(pad_len LESS 1)
            set(pad_len 1)
        endif()
        string(REPEAT " " ${pad_len} padding)

        string(APPEND output_lines "/* ${msg_desc} */\n")
        string(APPEND output_lines "enum { ${prefix}${msg_name}${padding}\t= ${errcode} };\t/* messid=${message_number} */\n\n")

        math(EXPR message_number "${message_number} + 1")
    endif()
endforeach()

# Write the output file
file(WRITE "${OUTPUT}" "\
/*
 * C error define file for facility ${facility_name} (${facility_code})
 * Generated by the CMake build system (equivalent to MESSGEN)
 */

#ifndef ${facility_name}_ERROR_DEFINED
#define ${facility_name}_ERROR_DEFINED

${output_lines}
#endif\t/* ${facility_name}_ERROR_DEFINED */
")

message(STATUS "Generated ${OUTPUT} from ${INPUT}")
